SELECT COLUMN_NAME AS 'NAME',
    COLUMN_TYPE AS 'TYPE',
    IS_NULLABLE AS 'NULL',
    COLUMN_KEY AS 'KEY',
    COLUMN_DEFAULT AS 'DEFAULT',
    EXTRA AS 'EXTRA'
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'alx_book_store'
    AND TABLE_NAME = 'Books';